--V1: Criação da tabela de gatos

CREATE TABLE gatos(
    ID_Gato INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome Varchar(50) NOT NULL,
    raca Varchar(50) NOT NULL,
    idade TINYINT NOT NULL
);